#!/bin/bash
set -ex
repo=`mktemp -d`
echo "Setting up charm dir for test" $repo

function on_exit()
{
    echo "Called"
    rm -Rf $repo
    rm -Rf cf-charms
}

trap on_exit EXIT

mkdir -p $repo/trusty

echo "Checking out cf charms"
git clone https://github.com/Altoros/cf-charms.git
cd cf-charms && git checkout dev && cd ..

cp -Rf cf-charms/charms/trusty/* $repo/trusty

# Use current/branch dir of cf-nats charm
rm -Rf $repo/trusty/cf-nats
cp -Rf ../cf-nats $repo/trusty

echo "Deploying cf"
export JUJU_REPOSITORY=$repo
juju-deployer -vdWc tests/02-simple.yml

echo "Verifying deployment"
curl http://`juju-deployer -f cloud-controller`:9022/info

