options:
  cc-use-nginx:
    type: boolean
    default: True
    description: "A short description of the configuration option"
  cc-port:
    type: int
    default: 9022
    description: "External Cloud Controller port"
  nats-port:
    type: int
    default: 4022
    description: "External NAT port"
  message_bus_servers:
    type: string
    default: "127.0.0.1:4222"
    description: "IP address and port of NATS server"
  external_domain:
    type: string
    default: "external_domain: api2.vcap.me"
    description: "tbd"
