#!/bin/bash
# config-changed occurs everytime a new configuration value is updated (juju set)

set -xe

export CONFIG_DIR=/var/lib/cloudfoundry/cfcloudcontroller/jobs/config
export CLOUD_CONTROLLER_NG_CONFIG=$CONFIG_DIR/cloud_controller_ng.yml
export CC_DIR=/var/lib/cloudfoundry/cfcloudcontroller

NATS_RUN_DIR=/var/vcap/sys/run/nats
NATS_LOG_DIR=/var/vcap/sys/log/nats

NATS_CONFIG="$CONFIG_DIR/nats.yml"

cat <<EOF > $NATS_CONFIG
---
net: `unit-get private-address`
port: 4222

pid_file: $NATS_RUN_DIR/nats.pid
log_file: $NATS_LOG_DIR/nats.log

authorization:
  user: admin
  password: "password"
  timeout: 5
EOF

DB_PATH=/var/lib/cloudfoundry/cfcloudcontroller/db/cc.db

sed -i "s|192.168.1.72|`unit-get private-address`|" $CLOUD_CONTROLLER_NG_CONFIG
sed -i "s|nats:nats@127.0.0.1|admin:password@`unit-get private-address`|" $CLOUD_CONTROLLER_NG_CONFIG
sed -i "s|postgres://ccadmin:password@127.0.0.1:5432/ccdb|sqlite://$DB_PATH|" $CLOUD_CONTROLLER_NG_CONFIG
sed -i "s|/var/vcap/jobs/cloud_controller_ng/config/runtimes.yml|/var/lib/cloudfoundry/cfcloudcontroller/jobs/config/runtimes.yml|" $CLOUD_CONTROLLER_NG_CONFIG
sed -i "s|/var/vcap/jobs/cloud_controller_ng/config/stacks.yml|/var/lib/cloudfoundry/cfcloudcontroller/jobs/config/stacks.yml|" $CLOUD_CONTROLLER_NG_CONFIG

