#!/bin/bash
# This must be renamed to the name of the relation. The goal here is to
# affect any change needed by relationships being formed, modified, or broken
# This script should be idempotent.

set -xe

DB_SCHEMA_USER=`relation-get schema_user`
DB_SCHEMA_PASSWORD=`relation-get schema_password`
DB_USER=`relation-get user`
DB_USER_PASSWORD=`relation-get password`
DB_DB=`relation-get database`
DB_HOST=`relation-get private-address`
DB_HOST_PORT=`relation-get port`
DB_HOST_STATE=`relation-get state`

juju-log $DB_SCHEMA_USER, $DB_SCHEMA_PASSWORD, $DB_USER, $DB_USER_PASSWORD, $DB_DB, $DB_HOST, $DB_HOST_PORT, $DB_HOST_STATE

export CONFIG_DIR=/var/lib/cloudfoundry/cfcloudcontroller/jobs/config
export CLOUD_CONTROLLER_NG_CONFIG=$CONFIG_DIR/cloud_controller_ng.yml
RUN_DIR=/var/vcap/sys/run/cloud_controller_ng
LOG_DIR=/var/vcap/sys/log/cloud_controller_ng
TMPDIR=/var/vcap/data/cloud_controller_ng/tmp
PIDFILE=$RUN_DIR/cloud_controller_ng.pid
NFS_SHARE=/var/vcap/nfs

mkdir -p $RUN_DIR
mkdir -p $LOG_DIR
mkdir -p $TMPDIR

mkdir -p /var/vcap/nfs/shared

sed -i "s|ccadmin:password@127.0.0.1:5432/ccdb|$DB_SCHEMA_USER:$DB_SCHEMA_PASSWORD@$DB_HOST:$DB_HOST_PORT/$DB_DB|" $CLOUD_CONTROLLER_NG_CONFIG



juju-log $JUJU_REMOTE_UNIT modified its settings
juju-log Relation settings:
relation-get
juju-log Relation members:
relation-list

