#!/bin/bash
# Here do anything needed to install the service
# i.e. apt-get install -y foo  or  bzr branch http://myserver/mycode /srv/webroot
# Make sure this hook exits cleanly and is idempotent, common problems here are
# failing to account for a debconf question on a dependency, or trying to pull
# from github without installing git first.

set -xe

# Installing packages
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4C430C3C2828E07D
add-apt-repository ppa:cf-charm/ppa
apt-get update
apt-get install -y curl git libgd3 libjbig0 libjpeg-turbo8 libjpeg8 libtiff5 libvpx1 nginx nginx-common nginx-extras libgd-tools nginx-doc fcgiwrap sqlite3 libsqlite3-dev
apt-get install -y cfcloudcontroller cfcloudcontrollerjob

#Creating necessary directory structure that all components can operate and write down their logs


mkdir -p /var/vcap/sys/run/cloud_controller_ng
mkdir -p /var/vcap/sys/run/nats
mkdir -p /var/vcap/sys/run/nginx_ccng

mkdir -p /var/vcap/sys/log/cloud_controller_ng
mkdir -p /var/vcap/sys/log/nats
mkdir -p /var/vcap/sys/log/nginx_ccng

mkdir -p /var/vcap/data/cloud_controller_ng/tmp
mkdir -p /var/vcap/data/cloud_controller_ng/tmp/uploads
mkdir -p /var/vcap/data/cloud_controller_ng/tmp/staged_droplet_uploads

mkdir -p /var/vcap/nfs/store

#Creating empty log files for the components
touch /var/vcap/sys/log/cloud_controller_ng/cloud_controller_ng.log
touch /var/vcap/sys/log/nats/nats.log
touch /var/vcap/sys/log/nginx_ccng/nginx.access.log
touch /var/vcap/sys/log/nginx_ccng/nginx.error.log

#Creating an empty database file for using with sqlite3
touch /var/lib/cloudfoundry/cfcloudcontroller/db/cc.db

#Creating an empty config file for NATS
touch /var/lib/cloudfoundry/cfcloudcontroller/jobs/config/nats.yml
