#!/bin/bash
# Here do anything needed to install the service
# i.e. apt-get install -y foo  or  bzr branch http://myserver/mycode /srv/webroot
# Make sure this hook exits cleanly and is idempotent, common problems here are
# failing to account for a debconf question on a dependency, or trying to pull
# from github without installing git first.

set -xe

apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4C430C3C2828E07D
add-apt-repository ppa:cf-charm/ppa
apt-get update
apt-get install -y curl git libgd3 libjbig0 libjpeg-turbo8 libjpeg8 libtiff5 libvpx1 nginx nginx-common nginx-full libgd-tools nginx-doc fcgiwrap
apt-get install -y cfcloudcontroller cfcloudcontrollerjob
