options:
  port:
    type: int
    default: 8080
    description: tbd
  user: 
    type: string
    default: "some_user"
    description: "tbd"
  pass: 
    type: string
    default: "some_password"
    description: "tbd"
