options:
  router_port:
    type: int
    default: 80
    description: 'Port nunmber that will be used to run router.'
  nats_address:
    type: string
    default: '10.0.3.137'
    description: 'Address to access NATS queueing messaging system.'
  nats_port:
    type: int
    default: 4022
    description: 'Port to access NATS queueing messaging system.'
  source:
    type: string
    default: 'ppa:cf-charm/ppa'
    description: |
      Optional configuration to support use of additional sources such as:
      .
        - ppa:myteam/ppa
        - cloud:precise-proposed/folsom
        - http://my.archive.com/ubuntu main
      .
      The last option should be used in conjunction with the key configuration
      option.
      .
      Note that a minimum ceph version of 0.48.2 is required for use with this
      charm which is NOT provided by the packages in the main Ubuntu archive
      for precise but is provided in the Folsom cloud archive.
  key:
    type: string
    default: '4C430C3C2828E07D'
    description: |
      Key ID to import to the apt keyring to support use with arbitary source
      configuration from outside of Launchpad archives or PPA's.

