---
pid: /var/run/uaa.pid
varz:
  username: _random_username_replaced_by_a_script_
  password: _random_password_replaced_by_a_script_
  type: uaa

logging:
  config: /var/lib/cloudfoundry/cfuaa/jobs/config/varz.log4j.properties
