#!/bin/bash
# Here do anything needed to install the service
# i.e. apt-get install -y foo  or  bzr branch http://myserver/mycode /srv/webroot
# Make sure this hook exits cleanly and is idempotent, common problems here are
# failing to account for a debconf question on a dependency, or trying to pull
# from github without installing git first.

set -xe

add-apt-repository ppa:cf-charm/ppa
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4C430C3C2828E07D
apt-get update
apt-get install -y cfcloudcontroller cfcloudcontrollerjob
